# Generated by Django 4.0.3 on 2022-04-27 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billignsaddress',
            old_name='CoroutineType',
            new_name='city',
        ),
    ]
