# Generated by Django 4.0.3 on 2022-04-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_payment', '0002_rename_coroutinetype_billignsaddress_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='billignsaddress',
            name='phone',
            field=models.CharField(blank=True, max_length=264),
        ),
    ]
